apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: india
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # We redirect to non-www if host is www.
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.corona-status.in') {
        rewrite ^ https://corona-status.in$request_uri permanent;
      }
spec:
  rules:
  - host: corona-status.in
    http:
      paths:
      - backend:
          serviceName: goodbye
          servicePort: 80
  - host: www.corona-status.in
    http:
      paths:
      - backend:
          serviceName: goodbye
          servicePort: 80
  tls:
  - hosts:
    - corona-status.in
    - www.corona-status.in
    secretName: in-coronastatus-cert-tls
