apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ country-name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # We redirect to non-www if host is www.
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.{{ domain }}') {
        rewrite ^ https://{{ domain }}$request_uri permanent;
      }
spec:
  rules:
  - host: {{ domain }}
    http:
      paths:
      - backend:
          serviceName: goodbye
          servicePort: 80
  - host: www.{{ domain }}
    http:
      paths:
      - backend:
          serviceName: goodbye
          servicePort: 80
  tls:
  - hosts:
    - {{ domain }}
    - www.{{ domain }}
    secretName: {{ country-code }}-coronastatus-cert-tls
